version: "3"

services:
  server:
    container_name: project_server
    build:
      context: .
      dockerfile: src/Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env
    command: >
      sh -c "npm install && NODE_ENV=dev npm run dev"
    depends_on:
      - postgres
  

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
